# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nonnan_ind <- function(x) {
    .Call('_BAREB_nonnan_ind', PACKAGE = 'BAREB', x)
}

rowsome <- function(x, ind) {
    .Call('_BAREB_rowsome', PACKAGE = 'BAREB', x, ind)
}

ton <- function(n) {
    .Call('_BAREB_ton', PACKAGE = 'BAREB', n)
}

colsome <- function(x, ind) {
    .Call('_BAREB_colsome', PACKAGE = 'BAREB', x, ind)
}

subsome <- function(x, ind) {
    .Call('_BAREB_subsome', PACKAGE = 'BAREB', x, ind)
}

dmvnrm_arma0 <- function(x, mean, sigma_square, logd = FALSE) {
    .Call('_BAREB_dmvnrm_arma0', PACKAGE = 'BAREB', x, mean, sigma_square, logd)
}

dmvnrm_arma <- function(x, mean, sigma_square, logd = FALSE) {
    .Call('_BAREB_dmvnrm_arma', PACKAGE = 'BAREB', x, mean, sigma_square, logd)
}

kernelC <- function(x, y, theta, tau) {
    .Call('_BAREB_kernelC', PACKAGE = 'BAREB', x, y, theta, tau)
}

updateC <- function(Z, theta, tau) {
    .Call('_BAREB_updateC', PACKAGE = 'BAREB', Z, theta, tau)
}

getind <- function(x, c) {
    .Call('_BAREB_getind', PACKAGE = 'BAREB', x, c)
}

ind <- function(x, index) {
    .Call('_BAREB_ind', PACKAGE = 'BAREB', x, index)
}

updateBeta <- function(X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mustar, mu, sigma, c, C, step, runif, n, m, T0, p, q, D, theta, tau) {
    .Call('_BAREB_updateBeta', PACKAGE = 'BAREB', X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mustar, mu, sigma, c, C, step, runif, n, m, T0, p, q, D, theta, tau)
}

updateBetanomiss <- function(X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mu, sigma, C, step, runif, n, m, T0, p, q, D, theta, tau) {
    .Call('_BAREB_updateBetanomiss', PACKAGE = 'BAREB', X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mu, sigma, C, step, runif, n, m, T0, p, q, D, theta, tau)
}

ind1 <- function(x, indi, index) {
    .Call('_BAREB_ind1', PACKAGE = 'BAREB', x, indi, index)
}

updateGamma <- function(X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mu, mustar, sigma, c, step, runif, n, m, T0, p, q, D, theta, tau) {
    .Call('_BAREB_updateGamma', PACKAGE = 'BAREB', X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mu, mustar, sigma, c, step, runif, n, m, T0, p, q, D, theta, tau)
}

updateGammanomiss <- function(X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mu, sigma, step, runif, n, m, T0, p, q, D, theta, tau) {
    .Call('_BAREB_updateGammanomiss', PACKAGE = 'BAREB', X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mu, sigma, step, runif, n, m, T0, p, q, D, theta, tau)
}

updateE <- function(Beta, Gamma, w, X, Y, Z, delta, E, R, S, Ds, mu, mustar, sigma, c, n, m, T0, p, q, D) {
    .Call('_BAREB_updateE', PACKAGE = 'BAREB', Beta, Gamma, w, X, Y, Z, delta, E, R, S, Ds, mu, mustar, sigma, c, n, m, T0, p, q, D)
}

updateEnomiss <- function(Beta, Gamma, w, X, Y, Z, delta, E, R, S, Ds, mu, sigma, n, m, T0, p, q, D) {
    .Call('_BAREB_updateEnomiss', PACKAGE = 'BAREB', Beta, Gamma, w, X, Y, Z, delta, E, R, S, Ds, mu, sigma, n, m, T0, p, q, D)
}

updatemu <- function(R, Z, X, Gamma, K, Beta, E, m, n, p, q) {
    .Call('_BAREB_updatemu', PACKAGE = 'BAREB', R, Z, X, Gamma, K, Beta, E, m, n, p, q)
}

Split <- function(w, K, Gamma, Beta, X, Y, Z, R, delta, mu, mu_star, c, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta = 1) {
    .Call('_BAREB_Split', PACKAGE = 'BAREB', w, K, Gamma, Beta, X, Y, Z, R, delta, mu, mu_star, c, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta)
}

Splitnomiss <- function(w, K, Gamma, Beta, X, Y, Z, R, delta, mu, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta = 1) {
    .Call('_BAREB_Splitnomiss', PACKAGE = 'BAREB', w, K, Gamma, Beta, X, Y, Z, R, delta, mu, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta)
}

Merge <- function(w, K, Gamma, Beta, X, Y, Z, R, delta, mu, mu_star, c, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta = 1) {
    .Call('_BAREB_Merge', PACKAGE = 'BAREB', w, K, Gamma, Beta, X, Y, Z, R, delta, mu, mu_star, c, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta)
}

Mergenomiss <- function(w, K, Gamma, Beta, X, Y, Z, R, delta, mu, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta = 1) {
    .Call('_BAREB_Mergenomiss', PACKAGE = 'BAREB', w, K, Gamma, Beta, X, Y, Z, R, delta, mu, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta)
}

RJi <- function(w, K, Gamma, Beta, X, Y, Z, R, delta, mu, mu_star, c, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta = 1) {
    .Call('_BAREB_RJi', PACKAGE = 'BAREB', w, K, Gamma, Beta, X, Y, Z, R, delta, mu, mu_star, c, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta)
}

RJinomiss <- function(w, K, Gamma, Beta, X, Y, Z, R, delta, mu, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta = 1) {
    .Call('_BAREB_RJinomiss', PACKAGE = 'BAREB', w, K, Gamma, Beta, X, Y, Z, R, delta, mu, sigma_square, C, theta, tau, m, n, q, T0, hyper_delta)
}

updateRi <- function(w, Gamma, Beta, Y, Z, delta, mu, mu_star, c, sigma_square, K, X, m, n, q) {
    .Call('_BAREB_updateRi', PACKAGE = 'BAREB', w, Gamma, Beta, Y, Z, delta, mu, mu_star, c, sigma_square, K, X, m, n, q)
}

updateRinomiss <- function(w, Gamma, Beta, Y, Z, delta, mu, sigma_square, K, X, m, n, q) {
    .Call('_BAREB_updateRinomiss', PACKAGE = 'BAREB', w, Gamma, Beta, Y, Z, delta, mu, sigma_square, K, X, m, n, q)
}

sample_int <- function(size, pro) {
    .Call('_BAREB_sample_int', PACKAGE = 'BAREB', size, pro)
}

updateR <- function(w, Gamma, Beta, Y, Z, delta, mu, mu_star, c, S, sigma_square, K, E, X, m, n, q, p, T0) {
    .Call('_BAREB_updateR', PACKAGE = 'BAREB', w, Gamma, Beta, Y, Z, delta, mu, mu_star, c, S, sigma_square, K, E, X, m, n, q, p, T0)
}

updateRnomiss <- function(w, Gamma, Beta, Y, Z, delta, mu, S, sigma_square, K, E, X, m, n, q, p, T0) {
    .Call('_BAREB_updateRnomiss', PACKAGE = 'BAREB', w, Gamma, Beta, Y, Z, delta, mu, S, sigma_square, K, E, X, m, n, q, p, T0)
}

updatemustar <- function(mu, c, n, T0, D) {
    .Call('_BAREB_updatemustar', PACKAGE = 'BAREB', mu, c, n, T0, D)
}

rtrun_norm <- function(mu, sigma, a, b) {
    .Call('_BAREB_rtrun_norm', PACKAGE = 'BAREB', mu, sigma, a, b)
}

updateZstar <- function(mu_star, delta, n, T0) {
    .Call('_BAREB_updateZstar', PACKAGE = 'BAREB', mu_star, delta, n, T0)
}

updatec <- function(Zstar, mu, D, sigmac, n, T0) {
    .Call('_BAREB_updatec', PACKAGE = 'BAREB', Zstar, mu, D, sigmac, n, T0)
}

updateBetanoDPP <- function(X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mustar, mu, sigma, c, step, runif, n, m, T0, p, q, D) {
    .Call('_BAREB_updateBetanoDPP', PACKAGE = 'BAREB', X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mustar, mu, sigma, c, step, runif, n, m, T0, p, q, D)
}

updateGammanoDPP <- function(X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mu, mustar, sigma, c, step, runif, n, m, T0, p, q, D) {
    .Call('_BAREB_updateGammanoDPP', PACKAGE = 'BAREB', X, Y, Z, delta, Beta, Gamma, E, R, S, Ds, mu, mustar, sigma, c, step, runif, n, m, T0, p, q, D)
}

updateRnoDPP <- function(Beta, Gamma, X, Y, Z, delta, E, R, S, Ds, mu, mustar, sigma, Ms, n, m, T0, p, q, D, Dmax = 10L) {
    .Call('_BAREB_updateRnoDPP', PACKAGE = 'BAREB', Beta, Gamma, X, Y, Z, delta, E, R, S, Ds, mu, mustar, sigma, Ms, n, m, T0, p, q, D, Dmax)
}

Split_empty <- function(w, K, Gamma, R, C, theta, tau, m, q, hyper_delta = 1) {
    .Call('_BAREB_Split_empty', PACKAGE = 'BAREB', w, K, Gamma, R, C, theta, tau, m, q, hyper_delta)
}

Merge_empty <- function(w, K, Gamma, R, C, theta, tau, m, q, hyper_delta = 1) {
    .Call('_BAREB_Merge_empty', PACKAGE = 'BAREB', w, K, Gamma, R, C, theta, tau, m, q, hyper_delta)
}

RJi_empty <- function(w, K, Gamma, R, C, theta, tau, m, q, hyper_delta = 1) {
    .Call('_BAREB_RJi_empty', PACKAGE = 'BAREB', w, K, Gamma, R, C, theta, tau, m, q, hyper_delta)
}

